// ============================================================
// lyrics.js — NIN song lyrics keyed by track filename
// Edit this file to update in-game quotes per song
// ============================================================

export const SONG_LYRICS = {
    'the-collector': [
        'I PICK THINGS UP I AM A COLLECTOR',
        'THINGS THEY TEND TO ACCUMULATE',
        'I HAVE THIS NET IT DRAGS BEHIND ME',
        'IT PICKS UP FEELINGS FOR ME TO FEED UPON',
        'PLENTY OF TIMES I WISH I COULD LET IT GO',
        'THEY START TO BREATHE AND THEY START TO GROW INSIDE ME',
        'THEY START TO MAKE ME THINK THINGS I DON\'T WANNA KNOW',
    ],
    'discipline': [
        'AND NOW IT\'S STARTING UP',
        'FEELS LIKE I\'M LOSING TOUCH',
        'NOTHING MATTERS TO ME',
        'NOTHING MATTERS AS MUCH',
        'I SEE YOU LEFT A MARK',
        'I DON\'T KNOW WHERE I END AND WHERE YOU BEGIN',
        'I NEED YOUR DISCIPLINE',
        'I NEED YOUR HELP',
        'YOU KNOW ONCE I START I CANNOT HELP MYSELF',
    ],
    'beginning-of-the-end': [
        'DOWN ON YOUR KNEES YOU\'LL BE LEFT BEHIND',
        'THIS IS THE BEGINNING',
        'WATCH WHAT YOU THINK THEY CAN READ YOUR MIND',
        'I GOT MY MARK SEE IT IN MY EYES',
        'MY REFLECTION I DON\'T RECOGNIZE',
    ],
    'capital-g': [
        'WELL I USED TO STAND FOR SOMETHING',
        'NOW I\'M ON MY HANDS AND KNEES',
        'TRADED IN MY GOD FOR THIS ONE',
        'AND HE SIGNS HIS NAME WITH A CAPITAL G',
        'CAPITAL G',
    ],
    'the-good-soldier': [
        'GUN FIRE IN THE STREET WHERE WE USED TO MEET',
        'ECHOES OUT A BEAT AND THE BASS GOES',
        'BOMB RIGHT OVER MY HEAD',
        'STEP OVER THE DEAD',
        'REMEMBER WHAT YOU SAID',
        'LIFE IS JUST A WAKING DREAM',
        'BUT THAT AIN\'T HOW IT SEEMS RIGHT HERE RIGHT NOW',
        'HOW CAN THIS BE REAL',
        'I CAN BARELY FEEL ANYMORE',
    ],
    'great-destroyer': [
        'I HOPE THEY CANNOT SEE',
        'THE LIMITLESS POTENTIAL LIVING INSIDE OF ME',
        'TO MURDER EVERYTHING',
        'I AM THE GREAT DESTROYER',
        'TURN IT UP',
        'LISTEN TO THE SHIT THEY PUMP INTO YOUR HEAD',
        'FILLING YOU WITH APATHY',
        'HOLD YOUR BREATH',
        'WAIT UNTIL YOU KNOW THE TIME IS RIGHT ON TIME',
        'THE END IS NEAR',
    ],
    'deep': [
        'BLANK STARE, DISREPAIR',
        'THERE\'S A BIG BLACK HOLE GONNA EAT ME UP SOMEDAY',
        'SOMEDAY FADES AWAY LIKE A MEMORY',
        'OR A PLACE THAT YOU\'D RATHER BE',
        'SOME PLACE LOST IN SPACE',
        'ITCH IN MY HEAD THAT\'S TELLING ME SOMEWHERE',
        'SOMEWHERE OUT THERE ANYWHERE',
        'I DON\'T CARE, GET ME OUT OF HERE',
    ],
    'not-so-pretty-now': [
        'WELL GO TAKE A LITTLE MORE',
        'WE\'LL SCRAPE YOU OFF THE FLOOR',
        'WE LOVE YOU ANYHOW',
        'BUT YOU\'RE NOT SO PRETTY NOW',
        'A GREAT BIG SUPERSTAR',
        'IS WHAT YOU THINK YOU ARE',
    ],
    'non-entity': [
        'THE SKY IS NOT THE SAME SHADE OF BLUE',
        'EVERY SINGLE THING I BELIEVE ISN\'T TRUE',
        'MISSING IN A MAZE OF MONOCHROME',
        'HOW DID I GET HERE HOW CAN I GO HOME',
        'THE ECHOES IN MY EYES OF ALL THEY USED TO SEE',
        'BURNING DOWN THE WORLD THE ASHES AND DEBRIS',
        'AND ALL THAT\'S LEFT OF ME A NON-ENTITY',
    ],
    'the-day-the-world-went-away': [
        'I\'D LISTEN TO THE WORDS HE\'D SAY',
        'BUT IN HIS VOICE I HEARD DECAY',
        'THE PLASTIC FACE FORCED TO PORTRAY',
        'ALL THE INSIDES LEFT COLD AND GRAY',
        'THERE IS A PLACE THAT STILL REMAINS',
        'IT EATS THE FEAR IT EATS THE PAIN',
        'THE SWEETEST PRICE HE\'LL HAVE TO PAY',
        'THE DAY THE WHOLE WORLD WENT AWAY',
    ],
    'me-im-not': [
        'AND IT\'S HAPPENING',
        'NEVER PLANNED ON THIS',
        'YOU GOT SOMETHING I NEED',
        'KIND OF DANGEROUS',
        'AND I\'M LOSING CONTROL',
        'I\'M NOT USED TO THIS',
        'WHAT YOU WANT FROM ME',
        'I CAN\'T SHUT IT OFF THIS THING I\'VE BEGUN',
        'IT\'S HARD TO TELL JUST WHERE IT\'S COMING FROM',
        'IT\'S HARD TO SEE WHAT I\'M CAPABLE OF',
        'IT\'S HARD TO BELIEVE JUST WHAT I\'VE BECOME',
    ],
};
